# Generated by Django 5.2.1 on 2025-05-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('cover_url', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('book_state', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
