# Generated by Django 5.2.1 on 2025-05-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_book_delete_books'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, related_name='borrowed_by', to='Books.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='Books.book'),
        ),
    ]
