# Generated by Django 5.2.1 on 2025-05-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_book_delete_books'),
        ('Users', '0002_user_borrowed_books_user_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='borrowed_books',
            field=models.ManyToManyField(to='Books.book'),
        ),
    ]
