# Generated by Django 5.2.1 on 2025-05-18 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_borrowed_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='borrowed_books',
        ),
    ]
