# Generated by Django 5.2.1 on 2025-05-18 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_book_delete_books'),
        ('Users', '0004_remove_user_borrowed_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='borrowed_books',
            field=models.ManyToManyField(related_name='borrowers', through='Users.UserBorrowedBook', to='Books.book'),
        ),
    ]
